### ISSUE TITLE
点击文件管理卡死

### ISSUE THREAD

**Issue by ad-calcium** [0linlin0/BurpExtender#2]
我这边测试的时候点击文件管理就卡死了，不知道其他人有没有这个情况
![image](https://user-images.githubusercontent.com/33044636/69515444-97352480-0f89-11ea-824e-e6707d17baa0.png)

**Comment by 0linlin0** [comment]
文件管理部分的源码我没有修改 我这边再测试下嘚

**Comment by 0linlin0** [comment]
hello 已经修复啦

AD钙奶 <notifications@github.com> 于2019年11月25日周一 下午1:44写道：

**Comment by 0linlin0** [comment]
> 我这边测试的时候点击文件管理就卡死了，不知道其他人有没有这个情况
> ![image](https://user-images.githubusercontent.com/33044636/69515444-97352480-0f89-11ea-824e-e6707d17baa0.png)

已经修复 感谢测试~
